export const LOAD_ORG_DETAILS = 'LOAD_ORG_DETAILS';
export const SUBMIT_ADMIN_LOGIN = 'SUBMIT_ADMIN_LOGIN';
export const ADMIN_USERNAME_ENTERED = 'ADMIN_USERNAME_ENTERED';
export const ADMIN_PASSWORD_ENTERED = 'ADMIN_PASSWORD_ENTERED';
export const FETCH_ADMINS = 'FETCH_ADMINS';