//TRANSACTIONS PAGE
export const TOGGLE_ORGANIZATION_DETAILS_ADMIN = 'TOGGLE_ORGANIZATION_DETAILS_ADMIN';
export const TOGGLE_ORGANIZATION_DETAILS_SRC = 'TOGGLE_ORGANIZATION_DETAILS_SRC';
export const TOGGLE_COMMENT_BOX = 'TOGGLE_COMMENT_BOX';
export const TOGGLE_SEE = 'TOGGLE_SEE';
export const TOGGLE_SEE_MORE = 'TOGGLE_SEE_MORE';
//WALLET PAGE
export const TOGGLE_PENDING_TRANSACTIONS_TAB = 'TOGGLE_PENDING_TRANSACTIONS_TAB';
export const TOGGLE_SIGNED_TRANSACTIONS_TAB = 'TOGGLE_SIGNED_TRANSACTIONS_TAB';
export const TRANSACTION_CLICKED = 'TRANSACTION_CLICKED';
export const SIGN_BUTTON_CLICKED = 'SIGN_BUTTON_CLICKED';
export const CANCEL_BUTTON_CLICKED = 'CANCEL_BUTTON_CLICKED';
export const SIGN_CLICKED = 'SIGN_CLICKED';
//SRC PAYMENT PAGE
export const SRC_PAYMENT_SUBMIT = 'SRC_PAYMENT_SUBMIT';
